# -*- coding: utf-8 -*-
"""exerc_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1puif63Wb8-UIy_sA4xLwNMZkXRlJoMUs
"""

import random

def gerarMatriz():

  linha = random.randint(3, 6)
  coluna = random.randint(3, 6)

  matriz = []

  for i in range(linha):
    linha = [0] * coluna

    for j in range(coluna):
      linha[j] = random.randint(0, 100)
    
    matriz.append(linha)

  return(matriz)

def main():
  matriz = gerarMatriz()
  listaReversa = []

  for i in range(len(matriz)):
    print(matriz[i])
    listaReversa = matriz[i]
    listaReversa.reverse()
    print(listaReversa)
    print('-----------------')

main()