# -*- coding: utf-8 -*-
"""exerc1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18k7XmeGy4H23nDifxAqs851DZ-WXyUzg
"""

#exerc_1
import random

linhas = int(input('numero de linhas: '))
colunas = int(input('numero de colunas: '))

def funcao(linhas, colunas):
  matriz = []

  for i in range(linhas):
    linha = [0] * colunas

    for j in range(len(linha)):
      linha[j] = random.randint(0, 999)
      
    matriz.append(linha)
    print(matriz[i])
  
 

funcao(linhas, colunas);