# -*- coding: utf-8 -*-
"""exerc_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1puif63Wb8-UIy_sA4xLwNMZkXRlJoMUs
"""

import random

def gerarMatriz():
  linhas = random.randint(3, 10)
  colunas = random.randint(3, 10)

  matriz = []

  for i in range(linhas):
    nova_linha = [0] * colunas

    for j in range(len(nova_linha)):
      nova_linha[j] = random.randint(1, 100)
    
    matriz.append(nova_linha)
  
  return(matriz)

def main():

  matriz = gerarMatriz()

  soma = 0

  for i in range(len(matriz)):
    for j in range(len(matriz[i])):
      soma = soma + matriz[i][j]

    print(matriz[i])
  print(soma)

main()