# -*- coding: utf-8 -*-
"""exerc_6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1puif63Wb8-UIy_sA4xLwNMZkXRlJoMUs
"""

import random

def gerarMatriz():
  linha = random.randint(2, 5)
  coluna = random.randint(2, 5)

  matriz = []

  for i in range(linha):
    nova_linha = [0] * coluna

    for j in range(len(nova_linha)):
      nova_linha[j] = random.randint(1, 50)

    matriz.append(nova_linha)
  
  return(matriz)

def main():
    
  matriz = gerarMatriz()

  lista = []
  soma = 0

  for i in range(len(matriz)):
    
    for j in range(len(matriz[i])):
      
      numero = matriz[i][j]
      soma = soma + numero
      
    lista.append(soma)
  
  print(lista)

main()