# -*- coding: utf-8 -*-
"""exerc1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GJKrp4m3E_dzZu26Ijr8HV1KEKgNnUrA
"""

import random

def gerar_matriz(linhas, colunas):
  matriz = [] 

  for i in range(linhas):
    nova_linha = [] 

    for j in range(colunas):
      numero = random.randint(1, 50)
      resto = numero % 2 
      
      if resto > 0 :
        nova_linha.append(numero)
    
    matriz.append(nova_linha)
    
    print(matriz[i])


gerar_matriz(5, 8);