Algoritmo "semnome"

Var

  senha: inteiro
Inicio
  escreval ("informe a senha <para sair -1>: ")
   leia (senha)

  repita


  se (senha) = 800 entao
  escreval ("senha correta, SUCESSO")
  senao
  escreval ("ERRO, informe a senha novamente: ")
  fimse
   escreval ("informe a senha <para sair -1>: ")
   leia (senha)
   escreval ("ERRO, pressione ESC e informe a senha novamente")
  ate (senha <>800)







Fimalgoritmo
