Algoritmo "semnome"

Var

   tinto, branco, rosa, total: real
   porcentagem_tinto, porcentagem_rosa, porcentagem_branco: real

Inicio
repita
escreval ("vinhos tinto: ")
leia (tinto)

escreval ("vinhos branco: ")
leia (branco)

escreval ("vinhos rosa: ")
leia (rosa)

total <- tinto + branco + rosa

porcentagem_tinto <- tinto * "100" / total
escreva (tinto)
ate (tinto < 0)




Fimalgoritmo




multiplicar