# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18k7XmeGy4H23nDifxAqs851DZ-WXyUzg
"""

#somar listas com funcao

import random

def main():
  lista_a = gerarlista()
  lista_b = gerarlista()

  lista_c = [0] * 100

  for i in range (len(lista_c)):
    lista_c[i]= lista_a[i] + lista_b[i]

  print(lista_a)
  print(lista_b)
  print(lista_c)

def mostrarlista():

  lista = gerarlista()

  for i in range (len(lista)):
    lista[i]=random.randint(-9999, 9999)
    
    print("O elemento %d esta no indice %d" % (lista[i], i))

def gerarlista():
  lista = [0] * 100
  for i in range (len(lista)):
    lista[i]=random.randint(-9999, 9999)
  
  return lista

mostrarlista();