# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18k7XmeGy4H23nDifxAqs851DZ-WXyUzg
"""

import random

lista_a = [0] * 100
lista_b = [0] * 100
lista_c = [0] * 100

for i in range (len(lista_a)):
  lista_a[i]=random.randint(-9999, 9999)

for i in range (len(lista_b)):
  lista_b[i]=random.randint(-9999, 9999)

for i in range (len(lista_a)):
  lista_c[i]= lista_a[i] + lista_b[i]

print(lista_a)
print(lista_b)
print(lista_c)