# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K3SdK8xxwQjpIU75Om9f3B5L9U_14_ea
"""

#Neste problema, deve-se ler o código de uma peça 1, o número de peças 1, o valor unitário de cada peça 1, o código de uma peça 2, o número de peças 2 e o valor unitário de cada peça 2. Após, calcule e mostre o valor a ser pago.

#Entrada
#O arquivo de entrada contém duas linhas de dados. Em cada linha haverá 3 valores, respectivamente dois inteiros e um valor com 2 casas decimais.

#Saída
#A saída deverá ser uma mensagem conforme o exemplo fornecido abaixo, lembrando de deixar um espaço após os dois pontos e um espaço após o "R$". O valor deverá ser apresentado com 2 casas após o ponto.

a = input().split()
b = input().split()

codPeca1, numPeca1, valorPeca1 = a
codPeca2, numPeca2, valorPeca2 = b

calc = (int(numPeca1) * float(valorPeca1)) + (int(numPeca2) * float(valorPeca2))

print("VALOR A PAGAR: R$ %.2f" % calc)