# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K3SdK8xxwQjpIU75Om9f3B5L9U_14_ea
"""

#Faça um programa que calcule e mostre o volume de uma esfera sendo fornecido o valor de seu raio (R). A fórmula para calcular o volume é: (4/3) * pi * R3. Considere (atribua) para pi o valor 3.14159.

#Dica: Ao utilizar a fórmula, procure usar (4/3.0) ou (4.0/3), pois algumas linguagens (dentre elas o C++), assumem que o resultado da divisão entre dois inteiros é outro inteiro.

#Entrada
#O arquivo de entrada contém um valor de ponto flutuante (dupla precisão), correspondente ao raio da esfera.

#Saída
#A saída deverá ser uma mensagem "VOLUME" conforme o exemplo fornecido abaixo, com um espaço antes e um espaço depois da igualdade. O valor deverá ser apresentado com 3 casas após o ponto.
#print("VALOR A PAGAR: R$ %.2f" % calc)
r = int(input())

print("VOLUME = %.3f" % ((4/3) * 3.14159 * (r ** 3)))