# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oz1lFrKmiMeEHXU54A9Zea-BmY-1oNAk
"""

#Faça um programa que leia três valores e apresente o maior dos três valores lidos seguido da mensagem “eh o maior”. Utilize a fórmula:

#Obs.: a fórmula apenas calcula o maior entre os dois primeiros (a e b). Um segundo passo, portanto é necessário para chegar no resultado esperado.

#Entrada
#O arquivo de entrada contém três valores inteiros.

#Saída
#Imprima o maior dos três valores seguido por um espaço e a mensagem "eh o maior".

#Exemplos de Entrada	Exemplos de Saída
#7 14 106 - 106 eh o maior
#217 14 6 - 217 eh o maior

a,b,c = map(int,input().split())
maiorAB = (a + b + abs(a - b)) / 2
maior = (maiorAB + c + abs(maiorAB - c)) / 2

print("%.0f eh o maior" % maior)