# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oz1lFrKmiMeEHXU54A9Zea-BmY-1oNAk
"""

#Leia um valor inteiro. A seguir, calcule o menor número de notas possíveis (cédulas) no qual o valor pode ser decomposto.
#As notas consideradas são de 100, 50, 20, 10, 5, 2 e 1. A seguir mostre o valor lido e a relação de notas necessárias.

#Entrada
#O arquivo de entrada contém um valor inteiro N (0 < N < 1000000).

#Saída
#Imprima o valor lido e, em seguida, a quantidade mínima de notas de cada tipo necessárias, conforme o exemplo fornecido.
#Não esqueça de imprimir o fim de linha após cada linha, caso contrário seu programa apresentará a mensagem: “Presentation Error”.
#5 nota(s) de R$ 100,00
#1 nota(s) de R$ 50,00
#1 nota(s) de R$ 20,00
#0 nota(s) de R$ 10,00
#1 nota(s) de R$ 5,00
#0 nota(s) de R$ 2,00
#1 nota(s) de R$ 1,00
n = int(input())




#print("%d nota(s) de R$ 100,00 \n%d nota(s) de R$ 50,00 \n%d nota(s) de R$ 20,00 \n%d nota(s) de R$ 10,00 \n%d nota(s) de R$ 5,00 \n%d nota(s) de R$ 2,00 \n%d nota(s) de R$ 1,00")