# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lRklYQnr44iVfSt5EW9vX4ACs4pc95D0
"""

#Leia um valor inteiro, que é o tempo de duração em segundos de um determinado evento em uma fábrica, e informe-o expresso no formato horas:minutos:segundos.

#Entrada
#O arquivo de entrada contém um valor inteiro N.

#Saída
#Imprima o tempo lido no arquivo de entrada (segundos), convertido para horas:minutos:segundos, conforme exemplo fornecido.

n = int(input())

horas = n / 3600
n = n % 3600

minutos = n / 60
n = n % 60

print("%d:%d:%d" % (int(horas), int(minutos), int(n)))