# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19G984Oqx96_qh550NJT0yM79pYCyuzEG
"""

# Com base na tabela abaixo, escreva um programa que leia o código de um item e a quantidade deste item.
# A seguir, calcule e mostre o valor da conta a pagar.

# Código | Especificação | Preço
# --------------------------------
#   1    | Cachorro Quente | R$ 4.00
#   2    | X-Salada          | R$ 4.50
#   3    | X-Bacon           | R$ 5.00
#   4    | Torrada simples | R$ 2.00
#   5    | Refrigerante      | R$ 1.50

# Entrada
# O arquivo de entrada contém dois valores inteiros correspondentes ao código e à quantidade de um item conforme tabela acima.

# Saída
# O arquivo de saída deve conter a mensagem "Total: R$ " seguido pelo valor a ser pago, com 2 casas após o ponto decimal.


preco_array = [4.00, 4.50, 5.00, 2.00, 1.50]

cod, qtd = map(int,input().split())

print("Total: R$ %.2f" % (preco_array[cod - 1] * qtd))