# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g851C9PNR0xih8OV-FuKLnNiHoZvB5vJ
"""

# Leia 2 valores inteiros (A e B). Após, o programa deve mostrar uma mensagem "Sao Multiplos" ou "Nao sao Multiplos",
# indicando se os valores lidos são múltiplos entre si.
#
# Entrada:
# A entrada contém valores inteiros.
#
# Saída:
# A saída deve conter uma das mensagens conforme descrito acima.
#
# Exemplo de Entrada    Exemplo de Saída
# 6 24                  Sao Multiplos
# 6 25                  Nao sao Multiplos

a, b = map(int, input().split())

if(b % a == 0 or a % b == 0):
  print('Sao Multiplos')
else:
  print('Nao sao Multiplos')