# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g851C9PNR0xih8OV-FuKLnNiHoZvB5vJ
"""

# Leia 3 valores de ponto flutuante A, B e C e ordene-os em ordem decrescente,
# de modo que o lado A representa o maior dos 3 lados. A seguir, determine o tipo de triângulo que estes três lados formam,
# com base nos seguintes casos, sempre escrevendo uma mensagem adequada:
#
# - Se A ≥ B+C, apresente a mensagem: NAO FORMA TRIANGULO
# - Se A^2 = B^2 + C^2, apresente a mensagem: TRIANGULO RETANGULO
# - Se A^2 > B^2 + C^2, apresente a mensagem: TRIANGULO OBTUSANGULO
# - Se A^2 < B^2 + C^2, apresente a mensagem: TRIANGULO ACUTANGULO
# - Se os três lados forem iguais, apresente a mensagem: TRIANGULO EQUILATERO
# - Se apenas dois dos lados forem iguais, apresente a mensagem: TRIANGULO ISOSCELES
#
# Entrada: A entrada contem três valores de ponto flutuante de dupla precisão A (0 < A) , B (0 < B) e C (0 < C).
# Saída: Imprima todas as classificações do triângulo especificado na entrada.
#
# Exemplo de Entrada    Exemplo de Saída
# 7.0 5.0 7.0           TRIANGULO ACUTANGULO
#                       TRIANGULO ISOSCELES
# 6.0 6.0 10.0          TRIANGULO OBTUSANGULO
#                       TRIANGULO ISOSCELES
# 6.0 6.0 6.0           TRIANGULO ACUTANGULO
#                       TRIANGULO EQUILATERO

x = list(map(float, input().split()))[:3]
ordem = sorted(x)
a = ordem[2]
b = ordem[1]
c = ordem[0]

if(a >= (b + c)):
  print('NAO FORMA TRIANGULO')
else:
  if((a * a) == ((b *b) + (c * c))):
    print('TRIANGULO RETANGULO')

  if((a * a) > ((b * b) + (c * c))):
    print('TRIANGULO OBTUSANGULO')

  if((a * a) < ((b *b) + (c * c))):
    print('TRIANGULO ACUTANGULO')

  if(a == b and b == c and a == c):
    print('TRIANGULO EQUILATERO')

  elif(a == b or a == c or b == c):
    print('TRIANGULO ISOSCELES')