# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g851C9PNR0xih8OV-FuKLnNiHoZvB5vJ
"""

# Leia a hora inicial e a hora final de um jogo. A seguir calcule a duração do jogo,
# sabendo que o mesmo pode começar em um dia e terminar em outro, tendo uma duração mínima de 1 hora e máxima de 24 horas.
#
# Entrada: A entrada contém dois valores inteiros representando a hora de início e a hora de fim do jogo.
# Saída: Apresente a duração do jogo conforme exemplo abaixo.
#
# Exemplo de Entrada    Exemplo de Saída
# 16 2                  O JOGO DUROU 10 HORA(S)
#
# 0 0                   O JOGO DUROU 24 HORA(S)
#
# 2 16                  O JOGO DUROU 14 HORA(S)

a,b = map(int, input().split())

if(a == b):
  print('O JOGO DUROU 24 HORA(S)')
elif(a > b):
  print('O JOGO DUROU %d HORA(S)' % ((24 - a) + b))
elif(a < b):
  print('O JOGO DUROU %d HORA(S)' % (b - a))