# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g851C9PNR0xih8OV-FuKLnNiHoZvB5vJ
"""

# Leia a hora inicial, minuto inicial, hora final e minuto final de um jogo.
# A seguir calcule a duração do jogo.
#
# Obs: O jogo tem duração mínima de um (1) minuto e duração máxima de 24 horas.
#
# Entrada: Quatro números inteiros representando a hora de início e fim do jogo.
# Saída: Mostre a seguinte mensagem: “O JOGO DUROU XXX HORA(S) E YYY MINUTO(S)”.
#
# Exemplo de Entrada    Exemplo de Saída
# 7 8 9 10              O JOGO DUROU 2 HORA(S) E 2 MINUTO(S)
#
# 7 7 7 7               O JOGO DUROU 24 HORA(S) E 0 MINUTO(S)
#
# 7 10 8 9              O JOGO DUROU 0 HORA(S) E 59 MINUTO(S)

hi, mi, hf, mf = map(int, input().split())
minutos = 0
horas = 0

if(mi < mf):
  minutos = (mf - mi)
elif(mi > mf):
  minutos = (((mi - mf) - 60) * (-1))
  if(hf == 0):
    hf = 23
  else:
    hf = hf - 1

if(hi < hf):
  horas = (hf - hi)
elif(hi > hf):
  horas = ((24 - hi) + hf)
elif(hi == hf and mi == mf):
  horas = 24



print('O JOGO DUROU %d HORA(S) E %d MINUTO(S)' % (horas, minutos))