# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WvEwhhlX02HMeIFN_6mLpQiCS0KEtpvC
"""

# Script para cálculo de aumento salarial conforme tabela de reajuste

# A empresa ABC resolveu conceder um aumento de salários a seus funcionários de acordo com a tabela abaixo:
#
# Salário                 Percentual de Reajuste
# 0 - 400.00              15%
# 400.01 - 800.00         12%
# 800.01 - 1200.00        10%
# 1200.01 - 2000.00       7%
# Acima de 2000.00        4%
#
# Leia o salário do funcionário e calcule e mostre o novo salário, bem como o valor de reajuste ganho e o índice reajustado, em percentual.
#
# Entrada:
# A entrada contém apenas um valor de ponto flutuante, com duas casas decimais.
#
# Saída:
# Imprima 3 linhas na saída: o novo salário, o valor ganho de reajuste (ambos devem ser apresentados com 2 casas decimais) e o percentual de reajuste ganho, conforme exemplo abaixo.
#
# Exemplo de Entrada     Exemplo de Saída
# 400.00
# Novo salario: 460.00
# Reajuste ganho: 60.00
# Em percentual: 15 %
#
# 800.01
# Novo salario: 880.01
# Reajuste ganho: 80.00
# Em percentual: 10 %
#
# 2000.00
# Novo salario: 2140.00
# Reajuste ganho: 140.00
# Em percentual: 7 %

salario = float(input())
percentual = 0
reajuste = 0.00

if(salario > 0.00 and salario <= 400.00):
  percentual = 15
  reajuste = (percentual / 100) * salario
elif(salario >= 400.01 and salario <= 800.00):
  percentual = 12
  reajuste = (percentual / 100) * salario
elif(salario >= 800.01 and salario <= 1200.00):
  percentual = 10
  reajuste = (percentual / 100) * salario
elif(salario >= 1200.01 and salario <= 2000.00):
  percentual = 7
  reajuste = (percentual / 100) * salario
elif(salario >= 2000.01):
  percentual = 4
  reajuste = (percentual / 100) * salario

print("Novo salario: %.2f" % (reajuste + salario))
print("Reajuste ganho: %.2f" % reajuste)
print("Em percentual:",percentual,"%")