# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WvEwhhlX02HMeIFN_6mLpQiCS0KEtpvC
"""

# Leia um número inteiro que representa um código de DDD para discagem interurbana. Em seguida, informe à qual cidade o DDD pertence, considerando a tabela abaixo:
#
# | DDD  | Cidade          |
# |------|------------------|
# | 11   | Sao Paulo       |
# | 21   | Rio de Janeiro  |
# | 31   | Belo Horizonte  |
# | 32   | Juiz de Fora    |
# | 61   | Brasilia        |
# | 71   | Salvador        |
# | 81   | Recife          |
# | 84   | Natal           |
# | 85   | Fortaleza       |
# | 92   | Manaus          |
# | 95   | Boa Vista       |
#
# Se a entrada for qualquer outro DDD que não esteja presente na tabela acima, o programa deverá informar:
# "DDD nao cadastrado"
#
# Entrada:
# A entrada consiste de um único valor inteiro.
#
# Saída:
# Imprima o nome da cidade correspondente ao DDD existente na entrada. Imprima "DDD nao cadastrado" caso não existir DDD correspondente ao número digitado.
#
# Exemplo de Entrada        Exemplo de Saída
# 11                        Sao Paulo

x = int(input())
conf = 0
ddd = [61, 71, 11, 21, 32, 19, 27, 31]
destination = ['Brasilia', 'Salvador', 'Sao Paulo', 'Rio de Janeiro', 'Juiz de Fora', 'Campinas', 'Vitoria', 'Belo Horizonte']

for i in range (len(ddd)):
  if(x == ddd[i]):
    print(destination[i])
    conf = conf + 1

if(conf == 0):
  print('DDD nao cadastrado')