# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WvEwhhlX02HMeIFN_6mLpQiCS0KEtpvC
"""

# Script para calcular o Imposto de Renda em Lisarb

# Em um país imaginário denominado Lisarb, todos os habitantes ficam felizes em pagar seus impostos, pois sabem que nele não existem políticos corruptos
# e os recursos arrecadados são utilizados em benefício da população, sem qualquer desvio. A moeda deste país é o Rombus, cujo símbolo é o R$.
#
# Leia um valor com duas casas decimais, equivalente ao salário de uma pessoa de Lisarb. Em seguida, calcule e mostre o valor que esta pessoa deve pagar de
# Imposto de Renda, segundo a tabela abaixo:
#
# | Faixa Salarial (R$)            | Percentual de Imposto |
# |--------------------------------|-----------------------|
# | de 0.00 a 2000.00              | Isento                |
# | de 2000.01 até 3000.00         | 8%                    |
# | de 3000.01 até 4500.00         | 18%                   |
# | acima de 4500.00               | 28%                   |
#
# Lembre que, se o salário for R$ 3002.00, a taxa que incide é de 8% apenas sobre R$ 1000.00, pois a faixa de salário que fica de R$ 0.00 até R$ 2000.00
# é isenta de Imposto de Renda. No exemplo fornecido (abaixo), a taxa é de 8% sobre R$ 1000.00 + 18% sobre R$ 2.00, o que resulta em R$ 80.36 no total.
# O valor deve ser impresso com duas casas decimais.
#
# Entrada:
# A entrada contém apenas um valor de ponto flutuante, com duas casas decimais.
#
# Saída:
# Imprima o texto "R$" seguido de um espaço e do valor total devido de Imposto de Renda, com duas casas após o ponto. Se o valor de entrada for menor
# ou igual a 2000, deverá ser impressa a mensagem "Isento".
#
# Exemplo de Entrada        Exemplo de Saída
# 3002.00                   R$ 80.36
# 1700.00                   Isento
# 4520.00                   R$ 355.60

salario = float(input())

if(salario >= 0.00 and salario <= 2000.00):
  print('Isento')
else:
  salarioComFaixa = salario - 2000.00

if(salario >= 2000.01 and salario <= 3000.00):
  print("R$ %.2f" % ((8.00 / 100.00) * salarioComFaixa))
elif(salario >= 3000.01 and salario <= 4500.00):
  print("R$ %.2f" % (((8.00 / 100.00) * 1000.00) + ((18.00 / 100.00) * (salario - 3000.00))))
elif(salario >= 4500.01):
  print("R$ %.2f" % float(((8.00 / 100.00) * 1000.00) + ((18.00 / 100.00) * ((salario - 3000.00) - (salario - 4500.00))) + ((28.00 / 100) * (salario - 4500.00))))