# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WvEwhhlX02HMeIFN_6mLpQiCS0KEtpvC
"""

# Script para converter um número inteiro em um mês do ano por extenso em inglês

# Leia um valor inteiro entre 1 e 12, inclusive. Correspondente a este valor, deve ser apresentado como resposta o mês do ano por extenso, em inglês,
# com a primeira letra maiúscula.
#
# Entrada:
# A entrada contém um único valor inteiro.
#
# Saída:
# Imprima por extenso o nome do mês correspondente ao número existente na entrada, com a primeira letra em maiúscula.
#
# Exemplo de Entrada      Exemplo de Saída
# 4                       April

index = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
meses = ["","January","February","March","April","May","June","July","August","September","October","November","December"]

x = int(input())

for i in range(0, 13):
  if(x == i):
    print(meses[i])