# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WvEwhhlX02HMeIFN_6mLpQiCS0KEtpvC
"""

# Programa para mostrar os números pares entre 1 e 100, inclusive.

# Entrada:
# Neste problema extremamente simples de repetição não há entrada.
#
# Saída:
# Imprima todos os números pares entre 1 e 100, inclusive se for o caso, um em cada linha.
#
# Exemplo de Saída:
# 2
# 4
# 6
# ...
# 100


for i in range(0,100):
  if(i % 2 == 0):
    print(i)