# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WvEwhhlX02HMeIFN_6mLpQiCS0KEtpvC
"""

# Programa para contar a quantidade de valores positivos lidos entre seis valores fornecidos.

# Entrada:
# Seis valores, negativos e/ou positivos.
#
# Saída:
# Imprima uma mensagem dizendo quantos valores positivos foram lidos.
#
# Exemplo de Entrada        Exemplo de Saída
# 7
# -5
# 6
# -3.4
# 4.6
# 12                        4 valores positivos

a=0
for i in range(6):
    if float(input()) > 0:
      a= a + 1

print("%d valores positivos" % a)