# -*- coding: utf-8 -*-
"""1172_beecrowd.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15ozPI9wKIJibDb_TW4AeW5mpMCuWlDMc
"""

x = [0] * 10

for i in range(len(x)):
  num = int(input('num: '))
  if num < 1:
    num = 1
  x[i] = num
  print(x)