# -*- coding: utf-8 -*-
"""1173_beecrowd.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15ozPI9wKIJibDb_TW4AeW5mpMCuWlDMc
"""

comprimento = int(input('tamanho da lista: '))

x = [0] * comprimento
numero = int(input('numero: '))

for i in range(len(x)):
  x[i] = numero
  numero = numero * 2
  print(x[i])