# -*- coding: utf-8 -*-
"""1174_beecrowd.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15ozPI9wKIJibDb_TW4AeW5mpMCuWlDMc
"""

import random

x = [0] * 100

posicoes = []
numeros = []

for i in range(len(x)):
  num = random.randint(0, 30) 
  x[i] = num

  if 10 > num:
    posicoes.append(i)
    numeros.append(num)

print(posicoes, len(posicoes))
print(numeros, len(numeros))