# -*- coding: utf-8 -*-
"""1175-beecrowd.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17lxjJTMX-jTvLPP39cyGte4G5Ez1-kWa
"""

import random

x = [0] * 20

w = []  

y = []

for b in range(len(x)):
  numero = random.randint(0, 10)
  x[b] = numero 
  for i in range(len(x), -1, -1):
    w.append(i)

calc = len(x) - 1
 
for g in range(calc, -1, -1):
  indice = x[g]
  y.append(indice)

print(x)
print(y)